### ISSUE TITLE
Maybe we should link the videos in the setup page

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/geospatial-workshop#11]
What do you think @srappel ?

**Comment by srappel** [comment]
Why not on the home page? Unless you mean just the setup videos.

**Comment by sstevens2** [comment]
I was thinking primarily of the setup videos.  Though we should think about the other lesson video as well.  I'm thinking maybe the links to the lesson videos should live in the lesson webpages, so we don't have to update them in multiple places if the links change.

**Comment by sstevens2** [comment]
Fixed by schedule addition
