### ISSUE TITLE
Reorder setup page to be less intimidating

### ISSUE THREAD

**Issue by srappel** [UW-Madison-DataScience/geospatial-workshop#4]
The setup page starts off with a table of software to install.  We don't want users thinking they need to install each package individually unless they want complete control of the install.

Users will still need to install R and RStudio even if using the KyngChaos package.  For windows, they will install R/RStudio and then install RTools. Linux users who already have QGIS will already have most packages needed.

**Comment by sstevens2** [comment]
Happy to review directions if needed.
