### ISSUE TITLE
Add a feedback mechanism to Setup

### ISSUE THREAD

**Issue by srappel** [UW-Madison-DataScience/geospatial-workshop#5]
"Did you have a problem getting your system ready for this workshop?"

Let us know: e-mail, form, something else?

What OS? Which software was the problem?

**Comment by sstevens2** [comment]
I'm thinking they could email `facilitator@datascience.wisc.edu`.  Clare and I both monitor that and if we need help will reach out the group.

**Comment by sstevens2** [comment]
If they want to fix the instructions though..maybe an issue would be better?  We could instead have them create an issue on the repo?
