### ISSUE TITLE
Update to use master branch instead and update contributing section

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/geospatial-workshop#7]

**Comment by srappel** [comment]
Is it okay that I'm still pushing commits to the gh-pages branch?

**Comment by sstevens2** [comment]
Yes, thanks for pushing to that one for now.  I'll fix this now.

**Comment by sstevens2** [comment]
@srappel I've updated the default and rendering branch to be `master`, left that as info in the readme, and deleted the `gh-pages` branch.  Work in master from now on.
